import turtle

turtle.down()
turtle.speed(speed=1)
turtle.screensize(canvwidth=800, canvheight=800, bg=None)
'''
letter a
turtle.left(65)
turtle.forward(200)
turtle.right(130)
turtle.forward(200)
turtle.right(115)
turtle.forward(30)
turtle.right(65)
turtle.forward(50)
turtle.left(65)
turtle.forward(65)
turtle.left(65)
turtle.forward(50)
turtle.right(65)
turtle.forward(30)
turtle.penup()
turtle.right(180)
turtle.forward(30)
turtle.left(65)
turtle.forward(75)
turtle.pendown()
turtle.forward(55)
turtle.right(130)
turtle.forward(55)
turtle.right(115)
turtle.forward(50)
'''
turtle.goto(0,0)

turtle.left(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(50)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(80)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.left(90)
turtle.circle(60,180)
turtle.left(180)
turtle.circle(40,180)
turtle.done()

